export const translateLangList = [
  /*
    {
        "name": "Test1 (sourceLangErrorMsg)",
        "code": "tst",
        "font_class_css": "font--default",
        "google_code": null,
        "papago_code": null,
        "bing_code": null,
        "baidu_code": null
    },
    {
        "name": "Test2 (langNotFoundErrorMsg)",
        "code": "tst2",
        "font_class_css": "font--default",
        "google_code": null,
        "papago_code": null,
        "bing_code": null,
        "baidu_code": null
    },
    */
  {
    name: 'Afrikaans',
    code: 'af',
    font_class_css: 'font--default',
    google_code: 'af',
    papago_code: null,
    bing_code: 'af',
    baidu_code: null,
  },
  {
    name: 'Albanian',
    code: 'sq',
    font_class_css: 'font--default',
    google_code: 'sq',
    papago_code: null,
    bing_code: 'sq',
    baidu_code: null,
  },
  {
    name: 'Amharic',
    code: 'am',
    font_class_css: 'font--ethiopic',
    google_code: 'am',
    papago_code: null,
    bing_code: 'am',
    baidu_code: null,
  },
  {
    name: 'Arabic',
    code: 'ar',
    font_class_css: 'font--arabic',
    google_code: 'ar',
    papago_code: null,
    bing_code: 'ar',
    baidu_code: 'ara',
  },
  {
    name: 'Armenian',
    code: 'hy',
    font_class_css: 'font--armenian',
    google_code: 'hy',
    papago_code: null,
    bing_code: 'hy',
    baidu_code: null,
  },
  {
    name: 'Assamese',
    code: 'as',
    font_class_css: 'font--bengali',
    google_code: 'as',
    papago_code: null,
    bing_code: 'as',
    baidu_code: null,
  },
  {
    name: 'Aymara',
    code: 'ay',
    font_class_css: 'font--default',
    google_code: 'ay',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Azerbaijani',
    code: 'az',
    font_class_css: 'font--default',
    google_code: 'az',
    papago_code: null,
    bing_code: 'az',
    baidu_code: null,
  },
  {
    name: 'Bambara',
    code: 'bm',
    font_class_css: 'font--default',
    google_code: 'bm',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Bashkir',
    code: 'ba',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'ba',
    baidu_code: null,
  },
  {
    name: 'Basque',
    code: 'eu',
    font_class_css: 'font--default',
    google_code: 'eu',
    papago_code: null,
    bing_code: 'eu',
    baidu_code: null,
  },
  {
    name: 'Belarusian',
    code: 'be',
    font_class_css: 'font--default',
    google_code: 'be',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Bengali',
    code: 'bn',
    font_class_css: 'font--bengali',
    google_code: 'bn',
    papago_code: null,
    bing_code: 'bn',
    baidu_code: null,
  },
  {
    name: 'Bhojpuri',
    code: 'bho',
    font_class_css: 'font--devanagari',
    google_code: 'bho',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Bosnian',
    code: 'bs',
    font_class_css: 'font--default',
    google_code: 'bs',
    papago_code: null,
    bing_code: 'bs',
    baidu_code: null,
  },
  {
    name: 'Bulgarian',
    code: 'bg',
    font_class_css: 'font--default',
    google_code: 'bg',
    papago_code: null,
    bing_code: 'bg',
    baidu_code: 'bul',
  },
  {
    name: 'Catalan',
    code: 'ca',
    font_class_css: 'font--default',
    google_code: 'ca',
    papago_code: null,
    bing_code: 'ca',
    baidu_code: null,
  },
  {
    name: 'Cebuano',
    code: 'ceb',
    font_class_css: 'font--default',
    google_code: 'ceb',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Chinese (Cantonese)',
    code: 'yue',
    font_class_css: 'font--hk',
    google_code: null,
    papago_code: null,
    bing_code: 'yue',
    baidu_code: 'yue',
  },
  {
    name: 'Chinese (Simplified)',
    code: 'zh-CN',
    font_class_css: 'font--sc',
    google_code: 'zh-CN',
    papago_code: 'zh-CN',
    bing_code: 'zh-Hans',
    baidu_code: 'zh',
  },
  {
    name: 'Chinese (Traditional)',
    code: 'zh-TW',
    font_class_css: 'font--tc',
    google_code: 'zh-TW',
    papago_code: null,
    bing_code: 'zh-Hant',
    baidu_code: 'cht',
  },
  {
    name: 'Chinese (Classical)',
    code: 'lzh',
    font_class_css: 'font--sc',
    google_code: null,
    papago_code: null,
    bing_code: 'lzh',
    baidu_code: 'wyw',
  },
  {
    name: 'Chuvash',
    code: 'cv',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Corsican',
    code: 'co',
    font_class_css: 'font--default',
    google_code: 'co',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Croatian',
    code: 'hr',
    font_class_css: 'font--default',
    google_code: 'hr',
    papago_code: null,
    bing_code: 'hr',
    baidu_code: null,
  },
  {
    name: 'Czech',
    code: 'cs',
    font_class_css: 'font--default',
    google_code: 'cs',
    papago_code: null,
    bing_code: 'cs',
    baidu_code: 'cs',
  },
  {
    name: 'Danish',
    code: 'da',
    font_class_css: 'font--default',
    google_code: 'da',
    papago_code: null,
    bing_code: 'da',
    baidu_code: 'dan',
  },
  {
    name: 'Dari',
    code: 'prs',
    font_class_css: 'font--arabic',
    google_code: null,
    papago_code: null,
    bing_code: 'prs',
    baidu_code: null,
  },
  {
    name: 'Dhivehi',
    code: 'dv',
    font_class_css: 'font--thaana',
    google_code: 'dv',
    papago_code: null,
    bing_code: 'dv',
    baidu_code: null,
  },
  {
    name: 'Dogri',
    code: 'doi',
    font_class_css: 'font--devanagari',
    google_code: 'doi',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Dutch',
    code: 'nl',
    font_class_css: 'font--default',
    google_code: 'nl',
    papago_code: null,
    bing_code: 'nl',
    baidu_code: 'nl',
  },
  {
    name: 'English',
    code: 'en',
    font_class_css: 'font--default',
    google_code: 'en',
    papago_code: 'en',
    bing_code: 'en',
    baidu_code: 'en',
  },
  {
    name: 'Esperanto',
    code: 'eo',
    font_class_css: 'font--default',
    google_code: 'eo',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Estonian',
    code: 'et',
    font_class_css: 'font--default',
    google_code: 'et',
    papago_code: null,
    bing_code: 'et',
    baidu_code: 'est',
  },
  {
    name: 'Faroese',
    code: 'fo',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'fo',
    baidu_code: null,
  },
  {
    name: 'Ewe',
    code: 'ee',
    font_class_css: 'font--default',
    google_code: 'ee',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Fijian',
    code: 'fj',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'fj',
    baidu_code: null,
  },
  {
    name: 'Filipino (Tagalog)',
    code: 'fil',
    font_class_css: 'font--default',
    google_code: 'fil',
    papago_code: null,
    bing_code: 'fil',
    baidu_code: null,
  },
  {
    name: 'Finnish',
    code: 'fi',
    font_class_css: 'font--default',
    google_code: 'fi',
    papago_code: null,
    bing_code: 'fi',
    baidu_code: 'fin',
  },
  {
    name: 'French',
    code: 'fr',
    font_class_css: 'font--default',
    google_code: 'fr',
    papago_code: 'fr',
    bing_code: 'fr',
    baidu_code: 'fra',
  },
  {
    name: 'French (Canada)',
    code: 'fr-ca',
    font_class_css: 'font--default',
    google_code: 'fr',
    papago_code: 'fr',
    bing_code: 'fr-ca',
    baidu_code: 'fra',
  },
  {
    name: 'Frisian',
    code: 'fy',
    font_class_css: 'font--default',
    google_code: 'fy',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Galician',
    code: 'gl',
    font_class_css: 'font--default',
    google_code: 'gl',
    papago_code: null,
    bing_code: 'gl',
    baidu_code: null,
  },
  {
    name: 'Georgian',
    code: 'ka',
    font_class_css: 'font--georgian',
    google_code: 'ka',
    papago_code: null,
    bing_code: 'ka',
    baidu_code: null,
  },
  {
    name: 'German',
    code: 'de',
    font_class_css: 'font--default',
    google_code: 'de',
    papago_code: 'de',
    bing_code: 'de',
    baidu_code: 'de',
  },
  {
    name: 'Greek',
    code: 'el',
    font_class_css: 'font--default',
    google_code: 'el',
    papago_code: null,
    bing_code: 'el',
    baidu_code: 'el',
  },
  {
    name: 'Guarani',
    code: 'gn',
    font_class_css: 'font--default',
    google_code: 'gn',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Gujarati',
    code: 'gu',
    font_class_css: 'font--gujarati',
    google_code: 'gu',
    papago_code: null,
    bing_code: 'gu',
    baidu_code: null,
  },
  {
    name: 'Haitian Creole',
    code: 'ht',
    font_class_css: 'font--default',
    google_code: 'ht',
    papago_code: null,
    bing_code: 'ht',
    baidu_code: null,
  },
  {
    name: 'Hausa',
    code: 'ha',
    font_class_css: 'font--default',
    google_code: 'ha',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Hawaiian',
    code: 'haw',
    font_class_css: 'font--default',
    google_code: 'haw',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Hebrew',
    code: 'he',
    font_class_css: 'font--hebrew',
    google_code: 'iw',
    papago_code: null,
    bing_code: 'he',
    baidu_code: null,
  },
  {
    name: 'Hindi',
    code: 'hi',
    font_class_css: 'font--devanagari',
    google_code: 'hi',
    papago_code: 'hi',
    bing_code: 'hi',
    baidu_code: null,
  },
  {
    name: 'Hmong',
    code: 'hmn',
    font_class_css: 'font--default',
    google_code: 'hmn',
    papago_code: null,
    bing_code: 'mww',
    baidu_code: null,
  },
  {
    name: 'Hungarian',
    code: 'hu',
    font_class_css: 'font--default',
    google_code: 'hu',
    papago_code: null,
    bing_code: 'hu',
    baidu_code: 'hu',
  },
  {
    name: 'Icelandic',
    code: 'is',
    font_class_css: 'font--default',
    google_code: 'is',
    papago_code: null,
    bing_code: 'is',
    baidu_code: null,
  },
  {
    name: 'Igbo',
    code: 'ig',
    font_class_css: 'font--default',
    google_code: 'ig',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Ilocano',
    code: 'ilo',
    font_class_css: 'font--default',
    google_code: 'ilo',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Indonesian',
    code: 'id',
    font_class_css: 'font--default',
    google_code: 'id',
    papago_code: 'id',
    bing_code: 'id',
    baidu_code: null,
  },
  {
    name: 'Inuinnaqtun',
    code: 'ikt',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'ikt',
    baidu_code: null,
  },
  {
    name: 'Inuktitut',
    code: 'iu',
    font_class_css: 'font--canadian-aboriginal',
    google_code: null,
    papago_code: null,
    bing_code: 'iu',
    baidu_code: null,
  },
  {
    name: 'Inuktitut (Latin)',
    code: 'iu-Latn',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'iu-Latn',
    baidu_code: null,
  },
  {
    name: 'Irish',
    code: 'ga',
    font_class_css: 'font--default',
    google_code: 'ga',
    papago_code: null,
    bing_code: 'ga',
    baidu_code: null,
  },
  {
    name: 'Italian',
    code: 'it',
    font_class_css: 'font--default',
    google_code: 'it',
    papago_code: 'it',
    bing_code: 'it',
    baidu_code: 'it',
  },
  {
    name: 'Japanese',
    code: 'ja',
    font_class_css: 'font--jp',
    google_code: 'ja',
    papago_code: 'ja',
    bing_code: 'ja',
    baidu_code: 'jp',
  },
  {
    name: 'Javanese',
    code: 'jv',
    font_class_css: 'font--default',
    google_code: 'jv',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Kannada',
    code: 'kn',
    font_class_css: 'font--kannada',
    google_code: 'kn',
    papago_code: null,
    bing_code: 'kn',
    baidu_code: null,
  },
  {
    name: 'Kazakh',
    code: 'kk',
    font_class_css: 'font--default',
    google_code: 'kk',
    papago_code: null,
    bing_code: 'kk',
    baidu_code: null,
  },
  {
    name: 'Khmer',
    code: 'km',
    font_class_css: 'font--khmer',
    google_code: 'km',
    papago_code: null,
    bing_code: 'km',
    baidu_code: null,
  },
  {
    name: 'Kinyarwanda',
    code: 'rw',
    font_class_css: 'font--default',
    google_code: 'rw',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Klingon (Latin)',
    code: 'tlh-Latn',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'tlh-Latn',
    baidu_code: null,
  },
  {
    name: 'Klingon (Tlhingan Hol)',
    code: 'tlh-Piqd',
    font_class_css: 'font--klingon',
    google_code: null,
    papago_code: null,
    bing_code: 'tlh-Latn',
    baidu_code: null,
  },
  {
    name: 'Konkani',
    code: 'gom',
    font_class_css: 'font--devanagari',
    google_code: 'gom',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Korean',
    code: 'ko',
    font_class_css: 'font--kr',
    google_code: 'ko',
    papago_code: 'ko',
    bing_code: 'ko',
    baidu_code: 'kor',
  },
  {
    name: 'Krio',
    code: 'kri',
    font_class_css: 'font--default',
    google_code: 'kri',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Kurdish',
    code: 'ku',
    font_class_css: 'font--arabic',
    google_code: 'ku',
    papago_code: null,
    bing_code: 'ku',
    baidu_code: null,
  },
  {
    name: 'Kurdish Central (Sorani)',
    code: 'ckb',
    font_class_css: 'font--arabic',
    google_code: 'ckb',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Kurdish Northern (Kurmanji)',
    code: 'kmr',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'kmr',
    baidu_code: null,
  },
  {
    name: 'Kyrgyz',
    code: 'ky',
    font_class_css: 'font--default',
    google_code: 'ky',
    papago_code: null,
    bing_code: 'ky',
    baidu_code: null,
  },
  {
    name: 'Lao',
    code: 'lo',
    font_class_css: 'font--lao',
    google_code: 'lo',
    papago_code: null,
    bing_code: 'lo',
    baidu_code: null,
  },
  {
    name: 'Latin',
    code: 'la',
    font_class_css: 'font--default',
    google_code: 'la',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Latvian',
    code: 'lv',
    font_class_css: 'font--default',
    google_code: 'lv',
    papago_code: null,
    bing_code: 'lv',
    baidu_code: null,
  },
  {
    name: 'Lingala',
    code: 'ln',
    font_class_css: 'font--default',
    google_code: 'ln',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Lithuanian',
    code: 'lt',
    font_class_css: 'font--default',
    google_code: 'lt',
    papago_code: null,
    bing_code: 'lt',
    baidu_code: null,
  },
  {
    name: 'Luganda',
    code: 'lg',
    font_class_css: 'font--default',
    google_code: 'lg',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Luxembourgish',
    code: 'lb',
    font_class_css: 'font--default',
    google_code: 'lb',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Macedonian',
    code: 'mk',
    font_class_css: 'font--default',
    google_code: 'mk',
    papago_code: null,
    bing_code: 'mk',
    baidu_code: null,
  },
  {
    name: 'Maithili',
    code: 'mai',
    font_class_css: 'font--devanagari',
    google_code: 'mai',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Malagasy',
    code: 'mg',
    font_class_css: 'font--default',
    google_code: 'mg',
    papago_code: null,
    bing_code: 'mg',
    baidu_code: null,
  },
  {
    name: 'Malay',
    code: 'ms',
    font_class_css: 'font--default',
    google_code: 'ms',
    papago_code: null,
    bing_code: 'ms',
    baidu_code: null,
  },
  {
    name: 'Malayalam',
    code: 'ml',
    font_class_css: 'font--malayalam',
    google_code: 'ml',
    papago_code: null,
    bing_code: 'ml',
    baidu_code: null,
  },
  {
    name: 'Maltese',
    code: 'mt',
    font_class_css: 'font--default',
    google_code: 'mt',
    papago_code: null,
    bing_code: 'mt',
    baidu_code: null,
  },
  {
    name: 'Maori',
    code: 'mi',
    font_class_css: 'font--devanagari',
    google_code: 'mi',
    papago_code: null,
    bing_code: 'mi',
    baidu_code: null,
  },
  {
    name: 'Marathi',
    code: 'mr',
    font_class_css: 'font--devanagari',
    google_code: 'mr',
    papago_code: null,
    bing_code: 'mr',
    baidu_code: null,
  },
  {
    name: 'Meiteilon (Manipuri)',
    code: 'mni-Mtei',
    font_class_css: 'font--bengali',
    google_code: 'mni-Mtei',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Mizo',
    code: 'lus',
    font_class_css: 'font--bengali',
    google_code: 'lus',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Mongolian',
    code: 'mn-Cyrl',
    font_class_css: 'font--default',
    google_code: 'mn',
    papago_code: null,
    bing_code: 'mn-Cyrl',
    baidu_code: null,
  },
  {
    name: 'Mongolian (Traditional)',
    code: 'mn-Mong',
    font_class_css: 'font--mongolian',
    google_code: null,
    papago_code: null,
    bing_code: 'mn-Mong',
    baidu_code: null,
  },
  {
    name: 'Myanmar (Burmese)',
    code: 'my',
    font_class_css: 'font--myanmar',
    google_code: 'my',
    papago_code: null,
    bing_code: 'my',
    baidu_code: null,
  },
  {
    name: 'Nepali',
    code: 'ne',
    font_class_css: 'font--devanagari',
    google_code: 'ne',
    papago_code: null,
    bing_code: 'ne',
    baidu_code: null,
  },
  {
    name: 'Norwegian',
    code: 'no',
    font_class_css: 'font--default',
    google_code: 'no',
    papago_code: null,
    bing_code: 'nb',
    baidu_code: null,
  },
  {
    name: 'Nyanja (Chichewa)',
    code: 'ny',
    font_class_css: 'font--default',
    google_code: 'ny',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Odia (Oriya)',
    code: 'or',
    font_class_css: 'font--oriya',
    google_code: 'or',
    papago_code: null,
    bing_code: 'or',
    baidu_code: null,
  },
  {
    name: 'Oromo',
    code: 'om',
    font_class_css: 'font--default',
    google_code: 'om',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Pashto',
    code: 'ps',
    font_class_css: 'font--arabic',
    google_code: 'ps',
    papago_code: null,
    bing_code: 'ps',
    baidu_code: null,
  },
  {
    name: 'Persian',
    code: 'fa',
    font_class_css: 'font--arabic',
    google_code: 'fa',
    papago_code: null,
    bing_code: 'fa',
    baidu_code: null,
  },
  {
    name: 'Polish',
    code: 'pl',
    font_class_css: 'font--default',
    google_code: 'pl',
    papago_code: null,
    bing_code: 'pl',
    baidu_code: 'pl',
  },
  {
    name: 'Portuguese (Brazil)',
    code: 'pt',
    font_class_css: 'font--default',
    google_code: 'pt',
    papago_code: 'pt',
    bing_code: 'pt',
    baidu_code: 'pt',
  },
  {
    name: 'Portuguese (Portugal)',
    code: 'pt-pt',
    font_class_css: 'font--default',
    google_code: 'pt',
    papago_code: 'pt',
    bing_code: 'pt-pt',
    baidu_code: 'pt',
  },
  {
    name: 'Punjabi',
    code: 'pa',
    font_class_css: 'font--gurmukhi',
    google_code: 'pa',
    papago_code: null,
    bing_code: 'pa',
    baidu_code: null,
  },
  {
    name: 'Quechua',
    code: 'qu',
    font_class_css: 'font--default',
    google_code: 'qu',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Queretaro Otomi',
    code: 'otq',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'otq',
    baidu_code: null,
  },
  {
    name: 'Romanian',
    code: 'ro',
    font_class_css: 'font--default',
    google_code: 'ro',
    papago_code: null,
    bing_code: 'ro',
    baidu_code: 'rom',
  },
  {
    name: 'Russian',
    code: 'ru',
    font_class_css: 'font--default',
    google_code: 'ru',
    papago_code: 'ru',
    bing_code: 'ru',
    baidu_code: 'ru',
  },
  {
    name: 'Samoan',
    code: 'sm',
    font_class_css: 'font--default',
    google_code: 'sm',
    papago_code: null,
    bing_code: 'sm',
    baidu_code: null,
  },
  {
    name: 'Sanskrit',
    code: 'sa',
    font_class_css: 'font--devanagari',
    google_code: 'sa',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Scots Gaelic',
    code: 'gd',
    font_class_css: 'font--default',
    google_code: 'gd',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Sepedi',
    code: 'nso',
    font_class_css: 'font--default',
    google_code: 'nso',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Serbian (Cyrillic)',
    code: 'sr-Cyrl',
    font_class_css: 'font--default',
    google_code: 'sr',
    papago_code: null,
    bing_code: 'sr-Cyrl',
    baidu_code: null,
  },
  {
    name: 'Serbian (Latin)',
    code: 'sr-Latn',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'sr-Latn',
    baidu_code: null,
  },
  {
    name: 'Sesotho',
    code: 'st',
    font_class_css: 'font--default',
    google_code: 'st',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Shona',
    code: 'sn',
    font_class_css: 'font--default',
    google_code: 'sn',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Sindhi',
    code: 'sd',
    font_class_css: 'font--arabic',
    google_code: 'sd',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Sinhala (Sinhalese)',
    code: 'si',
    font_class_css: 'font--sinhala',
    google_code: 'si',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Slovak',
    code: 'sk',
    font_class_css: 'font--default',
    google_code: 'sk',
    papago_code: null,
    bing_code: 'sk',
    baidu_code: null,
  },
  {
    name: 'Slovenian',
    code: 'sl',
    font_class_css: 'font--default',
    google_code: 'sl',
    papago_code: null,
    bing_code: 'sl',
    baidu_code: 'slo',
  },
  {
    name: 'Somali',
    code: 'so',
    font_class_css: 'font--default',
    google_code: 'so',
    papago_code: null,
    bing_code: 'so',
    baidu_code: null,
  },
  {
    name: 'Spanish',
    code: 'es',
    font_class_css: 'font--default',
    google_code: 'es',
    papago_code: 'es',
    bing_code: 'es',
    baidu_code: 'spa',
  },
  {
    name: 'Sundanese',
    code: 'su',
    font_class_css: 'font--sundanese',
    google_code: 'su',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Swahili',
    code: 'sw',
    font_class_css: 'font--default',
    google_code: 'sw',
    papago_code: null,
    bing_code: 'sw',
    baidu_code: null,
  },
  {
    name: 'Swedish',
    code: 'sv',
    font_class_css: 'font--default',
    google_code: 'sv',
    papago_code: null,
    bing_code: 'sv',
    baidu_code: 'swe',
  },
  {
    name: 'Tagalog (Filipino)',
    code: 'tl',
    font_class_css: 'font--tagalog',
    google_code: 'tl',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Tahiti',
    code: 'ty',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'ty',
    baidu_code: null,
  },
  {
    name: 'Tajik',
    code: 'tg',
    font_class_css: 'font--default',
    google_code: 'tg',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Tamil',
    code: 'ta',
    font_class_css: 'font--tamil',
    google_code: 'ta',
    papago_code: null,
    bing_code: 'ta',
    baidu_code: null,
  },
  {
    name: 'Tatar',
    code: 'tt',
    font_class_css: 'font--default',
    google_code: 'tt',
    papago_code: null,
    bing_code: 'tt',
    baidu_code: null,
  },
  {
    name: 'Telugu',
    code: 'te',
    font_class_css: 'font--telugu',
    google_code: 'te',
    papago_code: null,
    bing_code: 'te',
    baidu_code: null,
  },
  {
    name: 'Thai',
    code: 'th',
    font_class_css: 'font--thai',
    google_code: 'th',
    papago_code: 'th',
    bing_code: 'th',
    baidu_code: 'th',
  },
  {
    name: 'Tibetan',
    code: 'bo',
    font_class_css: 'font--tibetan',
    google_code: null,
    papago_code: null,
    bing_code: 'bo',
    baidu_code: null,
  },
  {
    name: 'Tigrinya',
    code: 'ti',
    font_class_css: 'font--ethiopic',
    google_code: 'ti',
    papago_code: null,
    bing_code: 'ti',
    baidu_code: null,
  },
  {
    name: 'Tongan',
    code: 'to',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'to',
    baidu_code: null,
  },
  {
    name: 'Tsonga',
    code: 'ts',
    font_class_css: 'font--default',
    google_code: 'ts',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Turkish',
    code: 'tr',
    font_class_css: 'font--default',
    google_code: 'tr',
    papago_code: null,
    bing_code: 'tr',
    baidu_code: null,
  },
  {
    name: 'Turkmen',
    code: 'tk',
    font_class_css: 'font--default',
    google_code: 'tk',
    papago_code: null,
    bing_code: 'tk',
    baidu_code: null,
  },
  {
    name: 'Twi (Akan)',
    code: 'ak',
    font_class_css: 'font--default',
    google_code: 'ak',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Ukrainian',
    code: 'uk',
    font_class_css: 'font--default',
    google_code: 'uk',
    papago_code: null,
    bing_code: 'uk',
    baidu_code: null,
  },
  {
    name: 'Upper Sorbian',
    code: 'hsb',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'hsb',
    baidu_code: null,
  },
  {
    name: 'Urdu',
    code: 'ur',
    font_class_css: 'font--urdu',
    google_code: 'ur',
    papago_code: null,
    bing_code: 'ur',
    baidu_code: null,
  },
  {
    name: 'Uyghur',
    code: 'ug',
    font_class_css: 'font--arabic',
    google_code: 'ug',
    papago_code: null,
    bing_code: 'ug',
    baidu_code: null,
  },
  {
    name: 'Uzbek',
    code: 'uz',
    font_class_css: 'font--default',
    google_code: 'uz',
    papago_code: null,
    bing_code: 'uz',
    baidu_code: null,
  },
  {
    name: 'Vietnamese',
    code: 'vi',
    font_class_css: 'font--default',
    google_code: 'vi',
    papago_code: 'vi',
    bing_code: 'vi',
    baidu_code: 'vie',
  },
  {
    name: 'Welsh',
    code: 'cy',
    font_class_css: 'font--default',
    google_code: 'cy',
    papago_code: null,
    bing_code: 'cy',
    baidu_code: null,
  },
  {
    name: 'Xhosa',
    code: 'xh',
    font_class_css: 'font--default',
    google_code: 'xh',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Yiddish',
    code: 'yi',
    font_class_css: 'font--hebrew',
    google_code: 'yi',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Yoruba',
    code: 'yo',
    font_class_css: 'font--default',
    google_code: 'yo',
    papago_code: null,
    bing_code: null,
    baidu_code: null,
  },
  {
    name: 'Yucatec Maya',
    code: 'yua',
    font_class_css: 'font--default',
    google_code: null,
    papago_code: null,
    bing_code: 'yua',
    baidu_code: null,
  },
  {
    name: 'Zulu',
    code: 'zu',
    font_class_css: 'font--default',
    google_code: 'zu',
    papago_code: null,
    bing_code: 'zu',
    baidu_code: null,
  },
];
